#Libraries  and Data importing

In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("C:/Users/user/Desktop/Dataets/Call_list.csv")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,NaN,NaN
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,NaN,NaN
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,NaN,NaN
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,NaN,NaN
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,NaN,NaN
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,NaN,NaN
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,NaN,NaN
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,NaN,NaN
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,NaN,NaN
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,NaN,NaN
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,NaN,NaN
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,NaN,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,NaN,NaN
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN

# modify Phone_Number column

In [97]:
df['Phone_Number']=df['Phone_Number'].str.replace('|','')
df['Phone_Number']=df['Phone_Number'].str.replace('/','')
df['Phone_Number']=df['Phone_Number'].str.replace('--','')
df['Phone_Number']=df['Phone_Number'].str.replace('-','')
df['Phone_Number']

C:\Users\user\AppData\Local\Temp\ipykernel_7648\1445893104.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Phone_Number']=df['Phone_Number'].str.replace('|','')

0     1235455421
1     1236439775
2     7066950392
3     1235432345
4     8766783469
5     3047622467
6            NaN
7     8766783469
8             Na
9     1235455421
10           NaN
11    7066950392
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17    7066950392
18            Na
19    8766783469
20    8766783469
Name: Phone_Number, dtype: object

# Giving Phone_Number column a standard form

In [98]:
df['Phone_Number']=df['Phone_Number'].apply(lambda x: str(x)[0:3]+'-'+str(x)[3:6]+'-'+str(x)[6:10])
df['Phone_Number']

0     123-545-5421
1     123-643-9775
2     706-695-0392
3     123-543-2345
4     876-678-3469
5     304-762-2467
6            nan--
7     876-678-3469
8             Na--
9     123-545-5421
10           nan--
11    706-695-0392
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17    706-695-0392
18            Na--
19    876-678-3469
20    876-678-3469
Name: Phone_Number, dtype: object

# splitting Address column and making 3 columns

In [99]:
df[['Street','City','Zip-Code']]=df['Address'].str.split(',',2,expand=True)
df

C:\Users\user\AppData\Local\Temp\ipykernel_7648\4138916928.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[['Street','City','Zip-Code']]=df['Address'].str.split(',',2,expand=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Unnamed: 8,Unnamed: 9,Street,City,Zip-Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,NaN,NaN,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False,NaN,NaN,93 West Main Street,None,None
2,1003,Walter,/White,706-695-0392,298 Drugs Driveway,N,NaN,True,NaN,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,NaN,NaN,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True,NaN,NaN,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,NaN,NaN,768 City Parkway,None,None
6,1007,Jeff,Winger,nan--,1209 South Street,No,No,False,NaN,NaN,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False,NaN,NaN,98 Clue Drive,None,None
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN,False,NaN,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,NaN,NaN,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No,True,NaN,NaN,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,True,NaN,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,NaN,NaN,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False,NaN,NaN,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,NaN,NaN,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,NaN,NaN,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,NaN,NaN,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,True,NaN,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,Na--,N/a,N/a,Yes,True,NaN,NaN,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN,910 Tatooine Road,Tatooine,None

# Removing uncessary columns

In [100]:
df=df.drop(columns=['Unnamed: 8','Unnamed: 9','Address'])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street,City,Zip-Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,/White,706-695-0392,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,nan--,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,Na--,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan--,Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,706-695-0392,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,Na--,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,True,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,Yes,N,True,910 Tatooine Road,Tatooine,None

# Dealing with NULL  Value

In [101]:
df=df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street,City,Zip-Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,True,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,No,Yes,False,93 West Main Street,,
2,1003,Walter,/White,706-695-0392,N,,True,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,True,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,True,768 City Parkway,,
6,1007,Jeff,Winger,nan--,No,No,False,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,No,False,98 Clue Drive,,
8,1009,Gandalf,,Na--,Yes,,False,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,Yes,No,True,25th Main Street,New York,
10,1011,Samwise,Gamgee,nan--,Yes,No,True,612 Shire Lane,Shire,
11,1012,Harry,...Potter,706-695-0392,Y,,True,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,Yes,N,False,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Yes,No,False,343 City Parkway,,
14,1015,Toby,Flenderson_,304-762-2467,N,No,False,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,No,N,False,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Yes,No,False,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,Y,,True,3498 Super Lane,,
18,1019,Creed,Braton,Na--,N/a,Yes,True,N/a,,
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,True,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876-678-3469,Yes,N,True,910 Tatooine Road,Tatooine,

# Change 'Yes' and 'No' to 'Y' and 'N' respectively in  'Paying Customer' and 'Do_Not_Contact columns.

In [102]:
df['Do_Not_Contact']=df['Do_Not_Contact'].replace('Yes','Y')
df['Do_Not_Contact']=df['Do_Not_Contact'].replace('No','N')
df['Paying Customer']=df['Do_Not_Contact'].replace('Yes','Y')
df['Paying Customer']=df['Do_Not_Contact'].replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street,City,Zip-Code
0,1001,Frodo,Baggins,123-545-5421,N,N,True,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,Y,Y,False,93 West Main Street,,
2,1003,Walter,/White,706-695-0392,,,True,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,Y,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,N,N,True,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,Y,Y,True,768 City Parkway,,
6,1007,Jeff,Winger,nan--,N,N,False,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,False,98 Clue Drive,,
8,1009,Gandalf,,Na--,,,False,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,N,N,True,25th Main Street,New York,
10,1011,Samwise,Gamgee,nan--,N,N,True,612 Shire Lane,Shire,
11,1012,Harry,...Potter,706-695-0392,,,True,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,N,N,False,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,N,N,False,343 City Parkway,,
14,1015,Toby,Flenderson_,304-762-2467,N,N,False,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,False,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,N,N,False,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,,,True,3498 Super Lane,,
18,1019,Creed,Braton,Na--,Y,Y,True,N/a,,
19,1020,Anakin,Skywalker,876-678-3469,N,N,True,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876-678-3469,N,N,True,910 Tatooine Road,Tatooine,

In [107]:
df=df[df['Do_Not_Contact']!='Y']
df=df[df['Phone_Number']!='nan--']
df=df[df['Phone_Number']!='Na--']
df=df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street,City,Zip-Code
0,1001,Frodo,Baggins,123-545-5421,N,N,True,123 Shire Lane,Shire,
1,1003,Walter,/White,706-695-0392,,,True,298 Drugs Driveway,,
2,1005,Jon,Snow,876-678-3469,N,N,True,123 Dragons Road,,
3,1008,Sherlock,Holmes,876-678-3469,N,N,False,98 Clue Drive,,
4,1010,Peter,Parker,123-545-5421,N,N,True,25th Main Street,New York,
5,1012,Harry,...Potter,706-695-0392,,,True,2394 Hogwarts Avenue,,
6,1013,Don,Draper,123-543-2345,N,N,False,2039 Main Street,,
7,1014,Leslie,Knope,876-678-3469,N,N,False,343 City Parkway,,
8,1015,Toby,Flenderson_,304-762-2467,N,N,False,214 HR Avenue,,
9,1016,Ron,Weasley,123-545-5421,N,N,False,2395 Hogwarts Avenue,,
10,1017,Michael,Scott,123-643-9775,N,N,False,121 Paper Avenue,Pennsylvania,
11,1018,Clark,Kent,706-695-0392,,,True,3498 Super Lane,,
12,1020,Anakin,Skywalker,876-678-3469,N,N,True,910 Tatooine Road,Tatooine,
13,1020,Anakin,Skywalker,876-678-3469,N,N,True,910 Tatooine Road,Tatooine,